import { createApp } from 'vue'
import router from '@/router'
import store from '@/store'
import App from './App.vue'
import 'normalize.css'
import 'element-plus/dist/index.css'
import '@/router/guide'
import '@/style/index.scss'
import 'virtual:svg-icons-register'
createApp(App).use(store).use(router).mount('#app')
